### ISSUE TITLE
Neon wallet 3 Linux executable

### ISSUE THREAD

**Issue by forall** [CityOfZion/neon-wallet-desktop#174]
Hello CityOfZion,

I have quesiton, neon wallet 3.x will be available for linux?

**Comment by thiagocbalducci** [comment]
Hi @forall ! Yes, we will have Linux support soon :)

**Comment by trancephorm** [comment]
The title here should be renamed to Neon wallet 3 Linux executable

**Comment by thiagocbalducci** [comment]
Hi @forall @trancephorm ! We wanted to invest a bit more time into testing that build before making it available, v3.1.0 will have a beta linux build available for those who want to try it.

It is worth noting that as a beta build, we recommend having your keys backed up before using it. We haven't found any issues with it yet, but it does not have the same level of coverage that Win and Mac builds have.

**Comment by forall** [comment]
@thiagocbalducci - can you share a beta version for linux, I would to testign that version.

**Comment by thiagocbalducci** [comment]
> @thiagocbalducci - can you share a beta version for linux, I would to testign that version.

Here you go :) https://github.com/CityOfZion/neon-wallet-desktop/releases/tag/v3.1.0

**Comment by thiagocbalducci** [comment]
Closing this issue as we already have a Linux build available in the latest version
