### ISSUE TITLE
DiscardVirtualMemory Kernel32.dll error

### ISSUE THREAD

**Issue by hocuspocus69** [CityOfZion/neon-wallet-desktop#183]
Trying new Neon wallet desktop
on windows 7 give me this error
is your new app compatible with Windows 7?

**Comment by thiagocbalducci** [comment]
Hi @hocuspocus69! Sorry about this, we don't support Windows 7 at this point.

**Comment by thiagocbalducci** [comment]
Closing this issue, feel free to reopen in case you have anything else to discuss here :)
